CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    email                VARCHAR(255) NOT NULL,
    first_name           VARCHAR(255) NOT NULL,
    identity_provider_id VARCHAR(255) NOT NULL,
    last_name            VARCHAR(255) NOT NULL,
    updated_at           TIMESTAMP(6) WITHOUT TIME ZONE,
    uuid                 UUID         NOT NULL,

    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_uuid UNIQUE (uuid),
    CONSTRAINT uk_users_identity_provider_id UNIQUE (identity_provider_id)
);